### PR TITLE
Fix the tests and user nomad's user stanza instead

### PR DESCRIPTION
**Pull request by jovandeginste**

### CODE REVIEW

**Comment by zstyblik** [comment]
I see and hopefully even understand what it does. Thank you. Note, however, that Docker driver in Nomad relies upon Docker Image setting the correct user, if I understand the documentation correctly and correct me if I'm wrong. I've also missed this part of documentation before. I cannot say whether this presents a drawback for some people or not.

Also, this explains why my Docker slaves were running as root user, because that's default user and user under which sshd is running under and Jenkins is SSH-ing in as jenkins with a matching key. No biggie, just providing explanation/personal observation.

**Comment by zstyblik** [comment]
@jovandeginste, please, let me know and I'll merge it in.

**Comment by zstyblik** [comment]
I've merged it not to block the progress. It's possible to revert it, if needed. Once again, thank you @jovandeginste.

**Comment by jovandeginste** [comment]
@zstyblik Not sure I understand your note.

As far as I understand, these things are to be considered:

* When building a Docker image, you can specify (more than once) a [`user` stanza](https://docs.docker.com/engine/reference/builder/#user)
  All subsequent stanza's will be executed as that user (if relevant). The `CMD` and `ENTRYPOINT` commands will be run with the final `USER`, unless overridden at runtime. The default user is `root:root`.
* When launching a Docker container, you can override the user as which the `CMD` or `ENTRYPOINT` are executed, using the [user flag](https://docs.docker.com/engine/reference/run/#user) (`--user`).
* As Nomad launches "jobs" (in the general sense), it is useful to specify as what user the job should run.
  This is relevant for raw `exec`, Docker containers, and in general any type of job. It provides the [`user` stanza](https://www.nomadproject.io/docs/job-specification/task.html#user) at task-level. In my tests yesterday it behaves as such (wrt. Docker containers):
  * No `User` stanza given: use the default Docker user as specified in the image
  * Any `User` stanza given will be equivalent to passing the `--user` parameter to the Docker `run` command
  * If the value of user is the empty string (ie. `--user=""`), Docker still uses the default user as specified in the image

  This led me to the implementation to always pass the `switchUser` as `user` in Nomad, even if it's empty (blank). The stack behaves as expected and does not change the user if it's blank. If you specify a user, it is passed to the Docker runtime engine. I did not test what happens if the user specified does not exist, but I don't think we should worry about that...

I hope I answered your question (and that my answer is not more confusing than clarifying :-))

**Comment by zstyblik** [comment]
@jovandeginste 

> Docker and rkt images specify their own **default** users.

*facepalm* as I've missed keyword default. Damn! And yes, I was like "oh, this doesn't make any sense to me. Why wouldn't you pass `--user` and rely on Docker Image?" Again, thank you for exhausting explanation and clarification. I'm off into the corner of shame since I've made a fool out of myself ... a bit :|

**Comment by jovandeginste** [comment]
@zstyblik Don't fret yourself over this - we all learn new stuff (almost) every day. If you were considering yourself an absolute expert in the matter, you should probably revisit that stance. Otherwise it's just a regular thing being active on the Internet :-)

**Pull request merged**
